# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addMaterialWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addMaterialWindow(object):
    def setupUi(self, addMaterialWindow):
        addMaterialWindow.setObjectName("addMaterialWindow")
        addMaterialWindow.resize(361, 467)
        self.verticalLayout = QtWidgets.QVBoxLayout(addMaterialWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(addMaterialWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.showMaterialLabel = QtWidgets.QLabel(addMaterialWindow)
        self.showMaterialLabel.setObjectName("showMaterialLabel")
        self.horizontalLayout.addWidget(self.showMaterialLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.prodAddMatTable = QtWidgets.QTableWidget(addMaterialWindow)
        self.prodAddMatTable.setObjectName("prodAddMatTable")
        self.prodAddMatTable.setColumnCount(2)
        self.prodAddMatTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.prodAddMatTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.prodAddMatTable.setHorizontalHeaderItem(1, item)
        self.prodAddMatTable.horizontalHeader().setDefaultSectionSize(150)
        self.prodAddMatTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.prodAddMatTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.addToBomButton = QtWidgets.QPushButton(addMaterialWindow)
        self.addToBomButton.setObjectName("addToBomButton")
        self.horizontalLayout_2.addWidget(self.addToBomButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(addMaterialWindow)
        QtCore.QMetaObject.connectSlotsByName(addMaterialWindow)

    def retranslateUi(self, addMaterialWindow):
        _translate = QtCore.QCoreApplication.translate
        addMaterialWindow.setWindowTitle(_translate("addMaterialWindow", "选择物料添加到产品"))
        self.label.setText(_translate("addMaterialWindow", "请从下方选择物料将其添加到产品："))
        self.showMaterialLabel.setText(_translate("addMaterialWindow", "\'产品名\'"))
        item = self.prodAddMatTable.horizontalHeaderItem(0)
        item.setText(_translate("addMaterialWindow", "物料ID"))
        item = self.prodAddMatTable.horizontalHeaderItem(1)
        item.setText(_translate("addMaterialWindow", "物料名称"))
        self.addToBomButton.setText(_translate("addMaterialWindow", "确定"))
