# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addMaterialWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addMaterialWindow(object):
    def setupUi(self, addMaterialWindow):
        addMaterialWindow.setObjectName("addMaterialWindow")
        addMaterialWindow.resize(400, 487)
        self.verticalLayout = QtWidgets.QVBoxLayout(addMaterialWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(addMaterialWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(addMaterialWindow)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(addMaterialWindow)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(addMaterialWindow)
        QtCore.QMetaObject.connectSlotsByName(addMaterialWindow)

    def retranslateUi(self, addMaterialWindow):
        _translate = QtCore.QCoreApplication.translate
        addMaterialWindow.setWindowTitle(_translate("addMaterialWindow", "选择物料添加到产品"))
        self.label.setText(_translate("addMaterialWindow", "请从下方选择物料将其添加到"))
        self.pushButton.setText(_translate("addMaterialWindow", "确定"))
