# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dataWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataPageWindow(object):
    def setupUi(self, dataPageWindow):
        dataPageWindow.setObjectName("dataPageWindow")
        dataPageWindow.resize(1000, 800)
        self.toMainWindowButton = QtWidgets.QPushButton(dataPageWindow)
        self.toMainWindowButton.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.toMainWindowButton.setObjectName("toMainWindowButton")
        self.tabChange = QtWidgets.QTabWidget(dataPageWindow)
        self.tabChange.setGeometry(QtCore.QRect(10, 40, 980, 750))
        self.tabChange.setObjectName("tabChange")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 131, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.loadUnMarkedDataByDir = QtWidgets.QPushButton(self.groupBox_3)
        self.loadUnMarkedDataByDir.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.loadUnMarkedDataByDir.setObjectName("loadUnMarkedDataByDir")
        self.dataMarkOutputShow = QtWidgets.QPlainTextEdit(self.tab_1)
        self.dataMarkOutputShow.setGeometry(QtCore.QRect(570, 40, 400, 690))
        self.dataMarkOutputShow.setObjectName("dataMarkOutputShow")
        self.clearDataMarkOutputShow = QtWidgets.QPushButton(self.tab_1)
        self.clearDataMarkOutputShow.setGeometry(QtCore.QRect(890, 10, 75, 23))
        self.clearDataMarkOutputShow.setObjectName("clearDataMarkOutputShow")
        self.toDataMarkWindowButton = QtWidgets.QPushButton(self.tab_1)
        self.toDataMarkWindowButton.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.toDataMarkWindowButton.setObjectName("toDataMarkWindowButton")
        self.tabChange.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 51))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.loadMarkedImageByDir = QtWidgets.QPushButton(self.groupBox)
        self.loadMarkedImageByDir.setGeometry(QtCore.QRect(10, 20, 71, 23))
        self.loadMarkedImageByDir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadMarkedImageByDir.setAutoFillBackground(False)
        self.loadMarkedImageByDir.setObjectName("loadMarkedImageByDir")
        self.datasetCollectOutputShow = QtWidgets.QPlainTextEdit(self.tab_2)
        self.datasetCollectOutputShow.setGeometry(QtCore.QRect(570, 40, 400, 690))
        self.datasetCollectOutputShow.setReadOnly(True)
        self.datasetCollectOutputShow.setObjectName("datasetCollectOutputShow")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 201, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.saveMarkedDataset = QtWidgets.QPushButton(self.groupBox_2)
        self.saveMarkedDataset.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.saveMarkedDataset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveMarkedDataset.setObjectName("saveMarkedDataset")
        self.clearDatasetCollectOutputShow = QtWidgets.QPushButton(self.tab_2)
        self.clearDatasetCollectOutputShow.setGeometry(QtCore.QRect(890, 10, 75, 23))
        self.clearDatasetCollectOutputShow.setObjectName("clearDatasetCollectOutputShow")
        self.tabChange.addTab(self.tab_2, "")
        self.tabChange.raise_()
        self.toMainWindowButton.raise_()

        self.retranslateUi(dataPageWindow)
        self.tabChange.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dataPageWindow)

    def retranslateUi(self, dataPageWindow):
        _translate = QtCore.QCoreApplication.translate
        dataPageWindow.setWindowTitle(_translate("dataPageWindow", "数据处理"))
        self.toMainWindowButton.setText(_translate("dataPageWindow", "回到主页"))
        self.groupBox_3.setTitle(_translate("dataPageWindow", "载入未打标数据方式"))
        self.loadUnMarkedDataByDir.setText(_translate("dataPageWindow", "打开文件夹"))
        self.clearDataMarkOutputShow.setText(_translate("dataPageWindow", "清除信息"))
        self.toDataMarkWindowButton.setText(_translate("dataPageWindow", "开始打标"))
        self.tabChange.setTabText(self.tabChange.indexOf(self.tab_1), _translate("dataPageWindow", "数据打标"))
        self.groupBox.setTitle(_translate("dataPageWindow", "载入打标数据方式"))
        self.loadMarkedImageByDir.setText(_translate("dataPageWindow", "打开文件夹"))
        self.groupBox_2.setTitle(_translate("dataPageWindow", "保存文件为数据集"))
        self.saveMarkedDataset.setText(_translate("dataPageWindow", "保存"))
        self.clearDatasetCollectOutputShow.setText(_translate("dataPageWindow", "清除信息"))
        self.tabChange.setTabText(self.tabChange.indexOf(self.tab_2), _translate("dataPageWindow", "数据集收集"))
