# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dataMarkWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataMarkWindow(object):
    def setupUi(self, dataMarkWindow):
        dataMarkWindow.setObjectName("dataMarkWindow")
        dataMarkWindow.resize(1000, 800)
        self.UnmarkedImageShow = QtWidgets.QLabel(dataMarkWindow)
        self.UnmarkedImageShow.setGeometry(QtCore.QRect(30, 130, 400, 400))
        self.UnmarkedImageShow.setText("")
        self.UnmarkedImageShow.setObjectName("UnmarkedImageShow")
        self.startShowUnmarkedImageButton = QtWidgets.QPushButton(dataMarkWindow)
        self.startShowUnmarkedImageButton.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.startShowUnmarkedImageButton.setObjectName("startShowUnmarkedImageButton")
        self.toDataWindowButton = QtWidgets.QPushButton(dataMarkWindow)
        self.toDataWindowButton.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.toDataWindowButton.setObjectName("toDataWindowButton")
        self.layoutWidget = QtWidgets.QWidget(dataMarkWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 630, 351, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qualifiedProductButton = QtWidgets.QPushButton(self.layoutWidget)
        self.qualifiedProductButton.setMinimumSize(QtCore.QSize(75, 0))
        self.qualifiedProductButton.setObjectName("qualifiedProductButton")
        self.buttonGroup = QtWidgets.QButtonGroup(dataMarkWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.qualifiedProductButton)
        self.horizontalLayout.addWidget(self.qualifiedProductButton)
        self.AClass = QtWidgets.QPushButton(self.layoutWidget)
        self.AClass.setMinimumSize(QtCore.QSize(75, 0))
        self.AClass.setObjectName("AClass")
        self.buttonGroup.addButton(self.AClass)
        self.horizontalLayout.addWidget(self.AClass)
        self.BClass = QtWidgets.QPushButton(self.layoutWidget)
        self.BClass.setMinimumSize(QtCore.QSize(75, 0))
        self.BClass.setObjectName("BClass")
        self.buttonGroup.addButton(self.BClass)
        self.horizontalLayout.addWidget(self.BClass)
        self.CClass = QtWidgets.QPushButton(self.layoutWidget)
        self.CClass.setMinimumSize(QtCore.QSize(75, 0))
        self.CClass.setObjectName("CClass")
        self.buttonGroup.addButton(self.CClass)
        self.horizontalLayout.addWidget(self.CClass)

        self.retranslateUi(dataMarkWindow)
        QtCore.QMetaObject.connectSlotsByName(dataMarkWindow)

    def retranslateUi(self, dataMarkWindow):
        _translate = QtCore.QCoreApplication.translate
        dataMarkWindow.setWindowTitle(_translate("dataMarkWindow", "数据打标"))
        self.startShowUnmarkedImageButton.setText(_translate("dataMarkWindow", "开始打标"))
        self.toDataWindowButton.setText(_translate("dataMarkWindow", "回到上一页"))
        self.qualifiedProductButton.setText(_translate("dataMarkWindow", "合格品"))
        self.AClass.setText(_translate("dataMarkWindow", "A类不合格品"))
        self.BClass.setText(_translate("dataMarkWindow", "B类不合格品"))
        self.CClass.setText(_translate("dataMarkWindow", "C类不合格品"))
