# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(272, 133)
        loginWindow.setMinimumSize(QtCore.QSize(272, 133))
        loginWindow.setMaximumSize(QtCore.QSize(272, 133))
        loginWindow.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(loginWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(loginWindow)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.cancelButton = QtWidgets.QPushButton(loginWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(loginWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.userNameEdit = QtWidgets.QLineEdit(loginWindow)
        self.userNameEdit.setEnabled(True)
        self.userNameEdit.setInputMask("")
        self.userNameEdit.setText("")
        self.userNameEdit.setFrame(True)
        self.userNameEdit.setCursorPosition(0)
        self.userNameEdit.setDragEnabled(False)
        self.userNameEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.userNameEdit.setClearButtonEnabled(False)
        self.userNameEdit.setObjectName("userNameEdit")
        self.verticalLayout.addWidget(self.userNameEdit)
        self.label_2 = QtWidgets.QLabel(loginWindow)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.passwordEdit = QtWidgets.QLineEdit(loginWindow)
        self.passwordEdit.setAutoFillBackground(False)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Dialog"))
        self.loginButton.setText(_translate("loginWindow", "登录"))
        self.cancelButton.setText(_translate("loginWindow", "取消"))
        self.label.setText(_translate("loginWindow", "用户名"))
        self.userNameEdit.setPlaceholderText(_translate("loginWindow", "User"))
        self.label_2.setText(_translate("loginWindow", "密码"))
        self.passwordEdit.setPlaceholderText(_translate("loginWindow", "Password"))
