# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 640)
        self.gridLayout_2 = QtWidgets.QGridLayout(mainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.changeUserButton = QtWidgets.QPushButton(mainWindow)
        self.changeUserButton.setObjectName("changeUserButton")
        self.horizontalLayout_2.addWidget(self.changeUserButton)
        self.changeUserPasswordButton = QtWidgets.QPushButton(mainWindow)
        self.changeUserPasswordButton.setObjectName("changeUserPasswordButton")
        self.horizontalLayout_2.addWidget(self.changeUserPasswordButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(mainWindow)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toProductManageWindowButton = QtWidgets.QPushButton(self.groupBox)
        self.toProductManageWindowButton.setMinimumSize(QtCore.QSize(100, 100))
        self.toProductManageWindowButton.setMaximumSize(QtCore.QSize(100, 100))
        self.toProductManageWindowButton.setObjectName("toProductManageWindowButton")
        self.horizontalLayout.addWidget(self.toProductManageWindowButton)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(81, 81))
        self.label.setMaximumSize(QtCore.QSize(81, 100))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.toDataWindowButton = QtWidgets.QPushButton(self.groupBox)
        self.toDataWindowButton.setMinimumSize(QtCore.QSize(100, 100))
        self.toDataWindowButton.setMaximumSize(QtCore.QSize(100, 100))
        self.toDataWindowButton.setObjectName("toDataWindowButton")
        self.horizontalLayout.addWidget(self.toDataWindowButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 100)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "主界面"))
        self.changeUserButton.setText(_translate("mainWindow", "切换用户"))
        self.changeUserPasswordButton.setText(_translate("mainWindow", "修改密码"))
        self.toProductManageWindowButton.setText(_translate("mainWindow", "产品管理"))
        self.label.setText(_translate("mainWindow", "->"))
        self.toDataWindowButton.setText(_translate("mainWindow", "数据处理"))
