# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\manageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manageWindow(object):
    def setupUi(self, manageWindow):
        manageWindow.setObjectName("manageWindow")
        manageWindow.resize(1000, 800)
        self.gridLayout_2 = QtWidgets.QGridLayout(manageWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(manageWindow)
        QtCore.QMetaObject.connectSlotsByName(manageWindow)

    def retranslateUi(self, manageWindow):
        _translate = QtCore.QCoreApplication.translate
        manageWindow.setWindowTitle(_translate("manageWindow", "管理界面"))
