# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\prodMatManageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_prodMatManageWindow(object):
    def setupUi(self, prodMatManageWindow):
        prodMatManageWindow.setObjectName("prodMatManageWindow")
        prodMatManageWindow.resize(800, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(prodMatManageWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignLeft)
        self.line = QtWidgets.QFrame(prodMatManageWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.productShowListTree = QtWidgets.QTreeWidget(prodMatManageWindow)
        self.productShowListTree.setColumnCount(2)
        self.productShowListTree.setObjectName("productShowListTree")
        self.productShowListTree.header().setDefaultSectionSize(300)
        self.verticalLayout.addWidget(self.productShowListTree)
        self.pushButton_7 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignLeft)
        self.line_2 = QtWidgets.QFrame(prodMatManageWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.productShowListTree_2 = QtWidgets.QTreeWidget(prodMatManageWindow)
        self.productShowListTree_2.setColumnCount(3)
        self.productShowListTree_2.setObjectName("productShowListTree_2")
        self.productShowListTree_2.header().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.productShowListTree_2)
        self.pushButton_8 = QtWidgets.QPushButton(prodMatManageWindow)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(prodMatManageWindow)
        QtCore.QMetaObject.connectSlotsByName(prodMatManageWindow)

    def retranslateUi(self, prodMatManageWindow):
        _translate = QtCore.QCoreApplication.translate
        prodMatManageWindow.setWindowTitle(_translate("prodMatManageWindow", "产品物料管理"))
        self.pushButton_6.setText(_translate("prodMatManageWindow", "返回主界面"))
        self.pushButton.setText(_translate("prodMatManageWindow", "新建产品"))
        self.pushButton_2.setText(_translate("prodMatManageWindow", "删除产品"))
        self.pushButton_3.setText(_translate("prodMatManageWindow", "向产品添加物料"))
        self.productShowListTree.headerItem().setText(0, _translate("prodMatManageWindow", "产品ID"))
        self.productShowListTree.headerItem().setText(1, _translate("prodMatManageWindow", "产品名称"))
        self.pushButton_7.setText(_translate("prodMatManageWindow", "保存"))
        self.pushButton_4.setText(_translate("prodMatManageWindow", "新建物料"))
        self.pushButton_5.setText(_translate("prodMatManageWindow", "物料打标"))
        self.productShowListTree_2.headerItem().setText(0, _translate("prodMatManageWindow", "物料ID"))
        self.productShowListTree_2.headerItem().setText(1, _translate("prodMatManageWindow", "物料名称"))
        self.productShowListTree_2.headerItem().setText(2, _translate("prodMatManageWindow", "隶属产品"))
        self.pushButton_8.setText(_translate("prodMatManageWindow", "保存"))
