# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\selectMat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selecetMat(object):
    def setupUi(self, selecetMat):
        selecetMat.setObjectName("selecetMat")
        selecetMat.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(selecetMat)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(selecetMat)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.matTableShow = QtWidgets.QTableWidget(selecetMat)
        self.matTableShow.setObjectName("matTableShow")
        self.matTableShow.setColumnCount(2)
        self.matTableShow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.matTableShow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.matTableShow.setHorizontalHeaderItem(1, item)
        self.matTableShow.horizontalHeader().setDefaultSectionSize(150)
        self.matTableShow.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.matTableShow)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.selectMatButton = QtWidgets.QPushButton(selecetMat)
        self.selectMatButton.setObjectName("selectMatButton")
        self.horizontalLayout_2.addWidget(self.selectMatButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(selecetMat)
        QtCore.QMetaObject.connectSlotsByName(selecetMat)

    def retranslateUi(self, selecetMat):
        _translate = QtCore.QCoreApplication.translate
        selecetMat.setWindowTitle(_translate("selecetMat", "选择物料"))
        self.label.setText(_translate("selecetMat", "请选择物料"))
        item = self.matTableShow.horizontalHeaderItem(0)
        item.setText(_translate("selecetMat", "物料ID"))
        item = self.matTableShow.horizontalHeaderItem(1)
        item.setText(_translate("selecetMat", "物料名称"))
        self.selectMatButton.setText(_translate("selecetMat", "确定"))
