# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\selectProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectProd(object):
    def setupUi(self, selectProd):
        selectProd.setObjectName("selectProd")
        selectProd.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(selectProd)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(selectProd)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.prodTableShow = QtWidgets.QTableWidget(selectProd)
        self.prodTableShow.setObjectName("prodTableShow")
        self.prodTableShow.setColumnCount(2)
        self.prodTableShow.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.prodTableShow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.prodTableShow.setHorizontalHeaderItem(1, item)
        self.prodTableShow.horizontalHeader().setDefaultSectionSize(150)
        self.prodTableShow.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.prodTableShow)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.selectProdButton = QtWidgets.QPushButton(selectProd)
        self.selectProdButton.setObjectName("selectProdButton")
        self.horizontalLayout_2.addWidget(self.selectProdButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(selectProd)
        QtCore.QMetaObject.connectSlotsByName(selectProd)

    def retranslateUi(self, selectProd):
        _translate = QtCore.QCoreApplication.translate
        selectProd.setWindowTitle(_translate("selectProd", "选择产品"))
        self.label.setText(_translate("selectProd", "请选择产品"))
        item = self.prodTableShow.horizontalHeaderItem(0)
        item.setText(_translate("selectProd", "产品ID"))
        item = self.prodTableShow.horizontalHeaderItem(1)
        item.setText(_translate("selectProd", "产品名称"))
        self.selectProdButton.setText(_translate("selectProd", "确定"))
