# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\voidWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_voidWindow(object):
    def setupUi(self, voidWindow):
        voidWindow.setObjectName("voidWindow")
        voidWindow.resize(1000, 800)
        self.gridLayout_2 = QtWidgets.QGridLayout(voidWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(voidWindow)
        QtCore.QMetaObject.connectSlotsByName(voidWindow)

    def retranslateUi(self, voidWindow):
        _translate = QtCore.QCoreApplication.translate
        voidWindow.setWindowTitle(_translate("voidWindow", "主界面"))
